"""jti instead of hash in sessions

Revision ID: 76df995c8287
Revises: 0b04698f0fd7
Create Date: 2026-05-19 19:08:12.761210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76df995c8287'
down_revision: Union[str, Sequence[str], None] = '0b04698f0fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('jti', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'sessions', ['jti'])
    op.drop_column('sessions', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_column('sessions', 'jti')
    # ### end Alembic commands ###
