name: Share token contract to other resources

on:
  push:
    branches:
      - master

jobs:
  publish-contract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout users service
        uses: actions/checkout@v4

      - name: Start app and export schema inside docker
        run: |
            docker compose up --build -d
            docker compose exec -T -w /app users_service sh -c "PYTHONPATH=/app .venv/bin/python -m schemas.export"
            docker cp users_service:/app/openapi.json schemas/openapi.json
            docker compose down

      - name: Checkout command bot service
        uses: actions/checkout@v4
        with:
          repository: "Felarm/command_bot"
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          path: "resource-service-dir"

      - name: Copy schema
        run: |
          mkdir -p resource-service-dir/schemas
          cp schemas/openapi.json resource-service-dir/schemas/users_service_openapi.json

      - name: Push schema file
        env:
          PAT_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
        run: |
          cd resource-service-dir
          git config --global user.name "github-actions-bot"
          git config --global user.email "github-actions-bot@github.com"
          git add schemas/users_service_openapi.json
          git diff-index --quiet HEAD || git commit -m "fetch latest contracts from users service"
          git remote set-url origin "https://x-access-token:${PAT_TOKEN}@://github.com"
          git push origin master


